[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
live_config_reload = true

[colors.bright]
black = "0x6e6a86"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.cursor]
cursor = "0x524f67"
text = "0xe0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "0x26233a"
blue = "0x9ccfd8"
cyan = "0xebbcba"
green = "0x31748f"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.selection]
background = "0x403d52"
text = "0xe0def4"

[colors.vi_mode_cursor]
cursor = "0x524f67"
text = "0xe0def4"

[env]
W3MIMGDISPLAY = "/usr/lib/w3m/w3mimgdisplay"

[font]
size = 12.0

#[font.bold]
#family = "Hack"
#style = "Bold"

#[font.bold_italic]
#family = "Hack"
#style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

#[font.italic]
#family = "Hack"
#style = "Italic"

#[font.normal]
#family = "Hack"
#style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window.padding]
x = 5
y = 5

[keyboard]
